### PR TITLE
ci: add github-workflow to matrix-build wheels

### PR DESCRIPTION
**Pull request by betaboon**
Hello,

As alot of people would want to use wheels from pypi I'm proposing switching to github-ci and using its matrix-build feature to generate wheels for all python-versions and operating-systems.

The contained github-workflow demonstrates how to do that.

Parts that are missing, as i first wanted to collect your input on this before going forward are:
- a job for running tests
- a job for publishing to pypi

I'm looking forward to hearing back from you

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks! Switching to github actions makes sense to me.

I suggest we first get to feature parity with the existing CI: https://github.com/ppwwyyxx/cocoapi/blob/master/.circleci/config.yml 

Then we can add releases. I think we can automating publishing to pypi whenever there is a new tag.

**Comment by ppwwyyxx** [comment]
Even for releases I also suggest we do it in steps:
* First automate source releases
* Then automate binary wheel releases as you requested

I'm not so confident that releasing binary wheels would work out-of-the-box. There were issues in the past about cython/numpy versions https://github.com/ppwwyyxx/cocoapi/pull/6/files that hopefully got fixed but I'm not sure.

**Comment by betaboon** [comment]
heya, that's great to hear.

do you want to take care about the test-job, or should i? (could take a couple of days until i find the time tho)

**Comment by ppwwyyxx** [comment]
I may not have time recently to implement these

**Comment by betaboon** [comment]
I'll do it when i find the time then :)

**Comment by johnnynunez** [comment]
https://github.com/ppwwyyxx/cocoapi/pull/16 done

**Comment by ppwwyyxx** [comment]
github actions were added now

**Pull request closed without merging**
