### PR TITLE
Add memory boundary guard for RLE decoding

### PR DESCRIPTION
**Pull request by maxclaey**
The current implementation of `rleDecode` does not check memory boundaries, causing unrecoverable segmentation faults for invalid RLE representations. This MR adds this check and will raise a catchable `ValueError` in this scenario rather than segfaulting.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Could you add a minimal test case in https://github.com/ppwwyyxx/cocoapi/blob/master/tests/test_cases.py? So that I know what error it's trying to fix

**Comment by maxclaey** [comment]
> 

Sure, I added a testcase!

**Comment by maxclaey** [comment]
@ppwwyyxx Does this testcase meet your request?

**Comment by ppwwyyxx** [comment]
Thanks a lot for fixing this!

**Comment by ppwwyyxx** [comment]
Included in the latest version 2.0.5 on pypi: https://pypi.org/project/pycocotools/

**Comment by maxclaey** [comment]
Welcome, thanks for merging!

**Pull request merged**
